# 按钮
UI_20251231_180011 = "取消"
# 消息
UI_20260103_120010 = "扫描归档专辑"
UI_20251201_110005 = "总共收集了 {} 张专辑，总共标记了 {} 个音轨。"
UI_20251224_210500 = "设置封面透明度：{}"
UI_20251231_180010 = "已保存元数据文件！"
# 标头
UI_20260101_112201 = "路径"
UI_20260101_112202 = "名字"
UI_20260101_112203 = "开始日期"
UI_20260101_112204 = "结束日期"
UI_20260101_112205 = "收集"
UI_20260101_112206 = "标记"
UI_20260101_112207 = "专辑"
UI_20260101_112208 = "编号"
UI_20260101_112209 = "日期"
UI_20260101_112210 = "标题"
UI_20260101_112211 = "大小"
UI_20260101_112212 = "艺术家"
# 文本占位
UI_20251231_170000 = "搜索名字..."
UI_20251231_180000 = "搜索专辑..."
UI_20251231_180001 = "搜索编号..."
UI_20251231_180002 = "搜索专辑..."
UI_20251231_180003 = "搜索日期..."
UI_20251231_180004 = "搜索音轨..."
UI_20251231_180005 = "搜索标题..."
UI_20251231_180006 = "搜索艺术家..."
UI_20251231_180007 = "搜索专辑..."
UI_20251231_180008 = "搜索标记..."
UI_20251231_180009 = "添加链接（{}）..."
# 按钮解释
UI_20260101_112220 = "向左翻页（Tab 键）"
UI_20260101_112221 = "向右翻页（Tab 键）"
UI_20260101_112222 = "下一首（Alt + ↓ 键）"
UI_20260101_112224 = "上一首（Alt + ↑ 键）"
UI_20260101_112225 = "播放/暂停（Space 键）"
# 菜单
UI_20260101_112226 = "打开元数据文件"
UI_20260101_112227 = "删除专辑"
UI_20260101_112228 = "打开专辑文件夹"
UI_20260101_112229 = "搜索封面"
UI_20260101_112231 = "复制文件名"
UI_20260101_112232 = "♡ 标记 听过（- 键）"
UI_20260101_112233 = "❤ 标记 喜欢（+ 键）"
UI_20260101_112234 = "标记 清除"
UI_20260101_112235 = ""
UI_20260101_112236 = ""
UI_20260101_112237 = ""
# 其他

################################################################################

WF_20251204_190036 = "归档音频资源"
WF_20251204_190037 = """
主题目录的父目录：
    例如输入             "D:\\ongaku-resource\\AnimeComicGame" ，
    将会在这里创建主题目录 "D:\\ongaku-resource\\AnimeComicGame\\Aチャンネル [A频道] [A-Channel]"
是否替换同级别资源：
    程序会固定使用 flac 替换 mp3 。
    当选择替换同级别资源时，会以 flac 替换 flac ，以 mp3 替换 mp3 。
"""
WF_20251204_190038 = "请输入元数据文件："
WF_20251204_190039 = "请输入音频资源父目录："
WF_20251204_190040 = "请输入主题目录的父目录："
WF_20251204_190041 = "匹配元数据时是否音轨数目必须相等（Y/N）（默认Y）："
WF_20251204_190042 = "请修改归档详细文件：{}"
WF_20251204_190043 = "是否修改完毕，开始应用归档（Y/N）（默认N）："
WF_20251204_190044 = "是否替换同级别资源（Y/N）（默认N）："
WF_20251204_190045 = "归档音频资源已完成。"

################################################################################

WF_20251204_194010 = "清理音频目录"
WF_20251204_194011 = "请输入音频资源父目录："
WF_20251204_194012 = "清理音频目录完成。"

################################################################################

WF_20251204_194120 = "创建本地 \"MusicBrainz\" 数据库"
WF_20251204_194121 = """
使用 MusicBrainz JSON Data Dumps 文件创建本地 Album 数据库。

转储文件目录：
    下载地址：https://data.metabrainz.org/pub/musicbrainz/data/json-dumps/
    下载如下文件： recording.tar.xz、release.tar.xz。
"""
WF_20251204_194122 = "请输入 MusicBrainz 转储文件目录："
WF_20251204_194123 = "是否删除已有的 MusicBrainz 数据库（Y/N）（默认N）："
WF_20251204_194124 = "已初始化 MusicBrainz 数据库。"
WF_20251204_194125 = "已启动 MusicBrainz 数据库。"
WF_20251204_194128 = "开始备份 MusicBrainz 数据库..."
WF_20251204_194127 = "已备份 MusicBrainz 数据库至 {}。"
WF_20251204_194126 = "已关闭 MusicBrainz 数据库。"

################################################################################

WF_20251204_194320 = "删除文件"
WF_20251204_194321 = """
删除路径文件或目录。不会挪至回收站，所以速度较快。
    """
WF_20251204_194322 = "请输入路径："
WF_20251204_194323 = "路径不存在。"
WF_20251204_194324 = "是否确认删除（Y/N）（默认N）："
WF_20251204_194325 = "已删除。耗时 {:.2f} 秒。"

################################################################################

WF_20251204_194420 = "导出喜欢的歌曲"
WF_20251204_194421 = """
导出目录路径：
    例如 D:\\ongaku-export
"""
WF_20251204_194422 = "请输入导出目录路径："
WF_20251204_194427 = "【{}/{}】资源不存在！{}\n是否继续（Y/N）（默认N）："
WF_20251204_194428 = "【{}/{}】封面不存在！{}\n是否继续（Y/N）（默认N）："
WF_20251204_194424 = "【{}/{}】已存在：{} -> {}"
WF_20251204_194425 = "【{}/{}】修改元数据：{}"
WF_20251204_194426 = "【{}/{}】重命名：{} -> {}"
WF_20251204_194423 = "【{}/{}】导出：{} -> {}"
WF_20251204_194429 = "是否删除导出目录中的多余文件：{} ："
WF_20251204_194431 = "压缩封面图像：{}"
WF_20251204_194432 = "导出喜欢的歌曲已完成。"

################################################################################

WF_20251204_194620 = "从本地音频获取专辑元数据"
WF_20251204_194621 = """
保存路径：
    若是文件夹，将会在其下生成新的元数据文件。
    若是已有的元数据文件路径，将会追加它未包含的专辑元数据

音频资源父目录：
"""
WF_20251204_194622 = "请输入保存路径："
WF_20251204_194623 = "请输入音频资源父目录："
WF_20251204_194624 = "解析完成。没有获得专辑元数据。"
WF_20251204_194625 = "解析完成。获得 {} 个专辑元数据，是否保存至 {} （Y/N）（默认Y）："
WF_20251204_194626 = "从本地音频获取专辑元数据完成。"

################################################################################

WF_20251204_194720 = "重新编码文本文件"
WF_20251204_194721 = """
扫描目录下的文本文件，尝试用不同的编码打开，找到它的正确的编码方式，然后以 UTF-8 编码保存。

父目录路径：
    将会扫描该目录中特定文件后缀的文件
文件后缀列表：
    将会处理父目录中该文件后缀的文件。多值用英文逗号隔开，例如 .txt,.cue,.log
保存文件前缀： 
    会新创建文件保存结果。
    输入如 __recoded_utf_8__ 时，D:\\download\\1.txt 重编码后会生成 D:\\download\\__recoded_utf_8__1.txt
"""
WF_20251204_194722 = "请输入父目录路径："
WF_20251204_194723 = "请输入文件后缀列表（默认为 .cue ）："
WF_20251204_194724 = "请输入保存文件前缀（默认为 __recoded_utf_8__）："
WF_20251204_194725 = """
a: 上一个编码 d: 下一个编码
w: 上一个文件 s: 下一个文件
p: 资源管理器打开路径
q: 退出
回车保存...
"""

################################################################################

WF_20251204_194820 = "从 \"同人音楽info\" 获取专辑元数据"
WF_20251204_194821 = """
保存路径：
    若是文件夹，将会在其下生成新的元数据文件。
    若是已有的元数据文件路径，将会追加它未包含的专辑元数据

同人音楽info url ：
    circle 页面，例如：https://www.dojin-music.info/circle/115
    cd 页面，例如：https://www.dojin-music.info/cd/458
    如果有多个 url ，请使用空格分隔，例如：
"""
WF_20251204_194822 = "请输入保存路径（默认 {}）："
WF_20251204_194823 = "请输入 同人音楽info url ："
WF_20251204_194824 = "不支持的 同人音楽info url 。"
WF_20251204_194825 = "成功获取 {:d} 张专辑元数据。元数据文件：{}"

################################################################################

WF_20251204_194920 = "从 \"VGMDB\" 获取专辑元数据"
WF_20251204_194921 = """
保存路径：
    若是文件夹，将会在其下生成新的元数据文件。
    若是已有的元数据文件路径，将会追加它未包含的专辑元数据

VGMDB url ：
    album 页面，例如：https://vgmdb.net/album/27425
    frachise 页面，例如：https://vgmdb.net/product/3559
    product 页面，例如：https://vgmdb.net/product/7750
    artist 页面，例如：https://vgmdb.net/artist/46
    搜索页面，例如：https://vgmdb.net/search?q=Yosuga+no+Sora&type=
    如果有多个 url ，请使用空格分隔，例如：https://vgmdb.net/product/3559 https://vgmdb.net/product/7750 https://vgmdb.net/search?q=Yosuga+no+Sora&type=
"""
WF_20251204_194922 = "请输入保存路径（默认 {}）："
WF_20251204_194923 = "请输入 VGMDB url ："
WF_20251204_194924 = "不支持的 VGMDB url 。"
WF_20251204_194925 = "成功获取 {:d} 张专辑元数据。元数据文件：{}"

################################################################################

WF_20251204_195320 = "从 \"MusicBrainz\" 获取专辑元数据"
WF_20251204_195321 = """
保存路径：
    若是文件夹，将会在其下生成新的元数据文件。
    若是已有的元数据文件路径，将会追加它未包含的专辑元数据

MusicBrainz url ：
    artist 页面，例如：https://beta.musicbrainz.org/artist/f960979c-fc79-4cef-8cf5-fda334e11445
    如果有多个 url ，请使用空格分隔，例如：url1 url2 url3
"""
WF_20251204_195322 = "请输入保存路径（默认 {}）："
WF_20251204_195323 = "请输入 MusicBrainz url ："
WF_20251204_195324 = "不支持的 MusicBrainz url 。"
WF_20251204_195325 = "本地 MusicBrainz 数据库 PGDATA 路径不存在。{}"
WF_20251204_195326 = "本地 MusicBrainz 数据库 PGDATA 路径存在。{}"
WF_20251204_195327 = "成功获取 {:d} 张专辑元数据。元数据文件：{}"
WF_20251204_195328 = "已启动 MusicBrainz 数据库。"
WF_20251204_195329 = "已关闭 MusicBrainz 数据库。"

################################################################################

WF_20251204_195520 = "从本地 MusicBrainz 数据库搜索专辑元数据"
WF_20251204_195521 = """
给定一个元数据文件，从本地 MusicBrainz 数据库中查询对应的专辑。
"""
WF_20251204_195522 = "本地 MusicBrainz 数据库 PGDATA 路径不存在。{}"
WF_20251204_195523 = "本地 MusicBrainz 数据库 PGDATA 路径存在。{}"
WF_20251204_195524 = "请输入待查询的元数据文件："
WF_20251204_195525 = "请输入筛选掩码列表 [catalognumber, date, date_int, track_count]（默认为 1000,0101）："
WF_20251204_195526 = "请输入排序掩码 [catalognumber, album, tracks_abstract]（默认为 111）："
WF_20251204_195527 = "请输入每张专辑查询结果数限制（默认为 10）："
WF_20251204_195528 = "已启动 MusicBrainz 数据库。"
WF_20251204_195529 = "成功获取 {:d} 张专辑元数据。元数据文件：{}"
WF_20251204_195530 = "已关闭 MusicBrainz 数据库。"

################################################################################

WF_20251204_195020 = "合并元数据"
WF_20251204_195021 = """
会对专辑列表根据总相似度最大算法，进行一一配对

元数据文件路径：
    如果有多个元数据文件，请使用 | 符号分隔，例如：D:\\Fetch-1.toml | D:\\Fetch-2.toml

link 关键字：
    例如来源关键字是 musicbrainz ，目标关键字是 vgmdb 时
    会过滤 links 中包含 musicbrainz ，不包含 vgmdb 的专辑作为合并来源
    会过滤 links 中包含 vgmdb ，不包含 musicbrainz 的专辑作为合并目标

元数据替换掩码：
    [catalognumber, date, album, tracks]
    例如，掩码 0001 代表只替换目标的 tracks 信息
    例如，掩码 0000 代表不替换任何信息，只是附加至 link
"""
WF_20251204_195022 = "请输入一个或多个元数据文件路径："
WF_20251204_195023 = "请输入作为来源的专辑的 link 的关键词："
WF_20251204_195024 = "请输入合并目标的专辑的 link 的关键词："
WF_20251204_195025 = "请至少输入一个 link 关键词。"
WF_20251204_195026 = "合并时是否来源与目标专辑的 catalognumber 必须相同（Y/N）（默认N）："
WF_20251204_195027 = "合并时是否来源与目标专辑的 tracks 数量必须相同（Y/N）（默认Y）："
WF_20251204_195028 = "请修改合并详细文件：{}"
WF_20251204_195029 = "是否修改完毕，开始应用合并（Y/N）（默认N）："
WF_20251204_195030 = "请输入来源合并至目标的元数据替换掩码（例如 0001）："
WF_20251204_195031 = "元数据替换掩码格式不正确。"
WF_20251204_195032 = "合并时是否允许自动替换目标中的空值（Y/N）（默认Y）："
WF_20251204_195033 = "合并详细文件被不正确的编辑。"
WF_20251204_195034 = "合并元数据成功。"

################################################################################

WF_20251204_195220 = "硬链接克隆"
WF_20251204_195221 = """
通过创建文件硬链接，镜像复制目标文件或文件夹。

原始路径：
    文件或文件夹，例如 D:\\1.txt ，例如 D:\\download。
目标父目录：
    必须与原始路径在同一磁盘，例如 D 盘。例如，输入 D:\\new\\ ，会在该父目录下创建同名对象。
"""
WF_20251204_195222 = "请输入原始文件或目录的路径："
WF_20251204_195223 = "请输入目标父目录："
WF_20251204_195224 = "原始路径不存在。"
WF_20251204_195225 = "硬链接拷贝已完成。{:d} 个文件，{:d} 个文件夹，耗时 {:.2f} 秒。"

################################################################################

WF_20251221_202001 = "归档资源"
WF_20251221_202002 = "已存在归档文件，请处理后按任意键继续：{}"
WF_20251221_202003 = "【{}/{}】归档：{} -> {}"










